#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Province {
    Bohemia,
    Budapest,
    Galicia,
    Trieste,
    Tyrolia,
    Vienna,
    Clyde,
    Edinburgh,
    Liverpool,
    London,
    Wales,
    Yorkshire,
    Brest,
    Burgundy,
    Gascony,
    Marseilles,
    Paris,
    Picardy,
    Berlin,
    Kiel,
    Munich,
    Prussia,
    Ruhr,
    Silesia,
    Apulia,
    Naples,
    Piedmont,
    Rome,
    Tuscany,
    Venice,
    Livonia,
    Moscow,
    Sevastopol,
    StPetersburg,
    Ukraine,
    Warsaw,
    Ankara,
    Armenia,
    Constantinople,
    Smyrna,
    Syria,
    Albania,
    Belgium,
    Bulgaria,
    Finland,
    Greece,
    Holland,
    Norway,
    NorthAfrica,
    Portugal,
    Rumania,
    Serbia,
    Spain,
    Sweden,
    Tunis,
    Denmark,
    AdriaticSea,
    AegeanSea,
    BalticSea,
    BarentsSea,
    BlackSea,
    EasternMediterranean,
    EnglishChannel,
    GulfOfBothnia,
    GulfOfLyon,
    HeligolandBight,
    IonianSea,
    IrishSea,
    MidAtlanticOcean,
    NorthAtlanticOcean,
    NorthSea,
    NorwegianSea,
    Skagerrak,
    TyrrhenianSea,
    WesternMediterranean,
}

impl core::fmt::Display for Province {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match &self {
            &Province::Bohemia => write!(f, "{}", "Bohemia"),
            &Province::Budapest => write!(f, "{}", "Budapest"),
            &Province::Galicia => write!(f, "{}", "Galicia"),
            &Province::Trieste => write!(f, "{}", "Trieste"),
            &Province::Tyrolia => write!(f, "{}", "Tyrolia"),
            &Province::Vienna => write!(f, "{}", "Vienna"),
            &Province::Clyde => write!(f, "{}", "Clyde"),
            &Province::Edinburgh => write!(f, "{}", "Edinburgh"),
            &Province::Liverpool => write!(f, "{}", "Liverpool"),
            &Province::London => write!(f, "{}", "London"),
            &Province::Wales => write!(f, "{}", "Wales"),
            &Province::Yorkshire => write!(f, "{}", "Yorkshire"),
            &Province::Brest => write!(f, "{}", "Brest"),
            &Province::Burgundy => write!(f, "{}", "Burgundy"),
            &Province::Gascony => write!(f, "{}", "Gascony"),
            &Province::Marseilles => write!(f, "{}", "Marseilles"),
            &Province::Paris => write!(f, "{}", "Paris"),
            &Province::Picardy => write!(f, "{}", "Picardy"),
            &Province::Berlin => write!(f, "{}", "Berlin"),
            &Province::Kiel => write!(f, "{}", "Kiel"),
            &Province::Munich => write!(f, "{}", "Munich"),
            &Province::Prussia => write!(f, "{}", "Prussia"),
            &Province::Ruhr => write!(f, "{}", "Ruhr"),
            &Province::Silesia => write!(f, "{}", "Silesia"),
            &Province::Apulia => write!(f, "{}", "Apulia"),
            &Province::Naples => write!(f, "{}", "Naples"),
            &Province::Piedmont => write!(f, "{}", "Piedmont"),
            &Province::Rome => write!(f, "{}", "Rome"),
            &Province::Tuscany => write!(f, "{}", "Tuscany"),
            &Province::Venice => write!(f, "{}", "Venice"),
            &Province::Livonia => write!(f, "{}", "Livonia"),
            &Province::Moscow => write!(f, "{}", "Moscow"),
            &Province::Sevastopol => write!(f, "{}", "Sevastopol"),
            &Province::StPetersburg => write!(f, "{}", "St Petersburg"),
            &Province::Ukraine => write!(f, "{}", "Ukraine"),
            &Province::Warsaw => write!(f, "{}", "Warsaw"),
            &Province::Ankara => write!(f, "{}", "Ankara"),
            &Province::Armenia => write!(f, "{}", "Armenia"),
            &Province::Constantinople => write!(f, "{}", "Constantinople"),
            &Province::Smyrna => write!(f, "{}", "Smyrna"),
            &Province::Syria => write!(f, "{}", "Syria"),
            &Province::Albania => write!(f, "{}", "Albania"),
            &Province::Belgium => write!(f, "{}", "Belgium"),
            &Province::Bulgaria => write!(f, "{}", "Bulgaria"),
            &Province::Finland => write!(f, "{}", "Finland"),
            &Province::Greece => write!(f, "{}", "Greece"),
            &Province::Holland => write!(f, "{}", "Holland"),
            &Province::Norway => write!(f, "{}", "Norway"),
            &Province::NorthAfrica => write!(f, "{}", "North Africa"),
            &Province::Portugal => write!(f, "{}", "Portugal"),
            &Province::Rumania => write!(f, "{}", "Rumania"),
            &Province::Serbia => write!(f, "{}", "Serbia"),
            &Province::Spain => write!(f, "{}", "Spain"),
            &Province::Sweden => write!(f, "{}", "Sweden"),
            &Province::Tunis => write!(f, "{}", "Tunis"),
            &Province::Denmark => write!(f, "{}", "Denmark"),
            &Province::AdriaticSea => write!(f, "{}", "Adriatic Sea"),
            &Province::AegeanSea => write!(f, "{}", "Aegean Sea"),
            &Province::BalticSea => write!(f, "{}", "Baltic Sea"),
            &Province::BarentsSea => write!(f, "{}", "Barents Sea"),
            &Province::BlackSea => write!(f, "{}", "Black Sea"),
            &Province::EasternMediterranean => write!(f, "{}", "Eastern Mediterranean"),
            &Province::EnglishChannel => write!(f, "{}", "English Channel"),
            &Province::GulfOfBothnia => write!(f, "{}", "Gulf of Bothnia"),
            &Province::GulfOfLyon => write!(f, "{}", "Gulf of Lyon"),
            &Province::HeligolandBight => write!(f, "{}", "Heligoland Bight"),
            &Province::IonianSea => write!(f, "{}", "Ionian Sea"),
            &Province::IrishSea => write!(f, "{}", "Irish Sea"),
            &Province::MidAtlanticOcean => write!(f, "{}", "Mid-Atlantic Ocean"),
            &Province::NorthAtlanticOcean => write!(f, "{}", "North Atlantic Ocean"),
            &Province::NorthSea => write!(f, "{}", "North Sea"),
            &Province::NorwegianSea => write!(f, "{}", "Norwegian Sea"),
            &Province::Skagerrak => write!(f, "{}", "Skagerrak"),
            &Province::TyrrhenianSea => write!(f, "{}", "Tyrrhenian Sea"),
            &Province::WesternMediterranean => write!(f, "{}", "Western Mediterranean"),
        }
    }
}

impl Province {
    fn country(&self) -> Option<super::country::Country> {
        match &self {
            &Province::Bohemia => Some(super::country::Country::Austria),
            &Province::Budapest => Some(super::country::Country::Austria),
            &Province::Galicia => Some(super::country::Country::Austria),
            &Province::Trieste => Some(super::country::Country::Austria),
            &Province::Tyrolia => Some(super::country::Country::Austria),
            &Province::Vienna => Some(super::country::Country::Austria),
            &Province::Clyde => Some(super::country::Country::England),
            &Province::Edinburgh => Some(super::country::Country::England),
            &Province::Liverpool => Some(super::country::Country::England),
            &Province::London => Some(super::country::Country::England),
            &Province::Wales => Some(super::country::Country::England),
            &Province::Yorkshire => Some(super::country::Country::England),
            &Province::Brest => Some(super::country::Country::France),
            &Province::Burgundy => Some(super::country::Country::France),
            &Province::Gascony => Some(super::country::Country::France),
            &Province::Marseilles => Some(super::country::Country::France),
            &Province::Paris => Some(super::country::Country::France),
            &Province::Picardy => Some(super::country::Country::France),
            &Province::Berlin => Some(super::country::Country::Germany),
            &Province::Kiel => Some(super::country::Country::Germany),
            &Province::Munich => Some(super::country::Country::Germany),
            &Province::Prussia => Some(super::country::Country::Germany),
            &Province::Ruhr => Some(super::country::Country::Germany),
            &Province::Silesia => Some(super::country::Country::Germany),
            &Province::Apulia => Some(super::country::Country::Italy),
            &Province::Naples => Some(super::country::Country::Italy),
            &Province::Piedmont => Some(super::country::Country::Italy),
            &Province::Rome => Some(super::country::Country::Italy),
            &Province::Tuscany => Some(super::country::Country::Italy),
            &Province::Venice => Some(super::country::Country::Italy),
            &Province::Livonia => Some(super::country::Country::Russia),
            &Province::Moscow => Some(super::country::Country::Russia),
            &Province::Sevastopol => Some(super::country::Country::Russia),
            &Province::StPetersburg => Some(super::country::Country::Russia),
            &Province::Ukraine => Some(super::country::Country::Russia),
            &Province::Warsaw => Some(super::country::Country::Russia),
            &Province::Ankara => Some(super::country::Country::Turkey),
            &Province::Armenia => Some(super::country::Country::Turkey),
            &Province::Constantinople => Some(super::country::Country::Turkey),
            &Province::Smyrna => Some(super::country::Country::Turkey),
            &Province::Syria => Some(super::country::Country::Turkey),
            &Province::Albania => None,
            &Province::Belgium => None,
            &Province::Bulgaria => None,
            &Province::Finland => None,
            &Province::Greece => None,
            &Province::Holland => None,
            &Province::Norway => None,
            &Province::NorthAfrica => None,
            &Province::Portugal => None,
            &Province::Rumania => None,
            &Province::Serbia => None,
            &Province::Spain => None,
            &Province::Sweden => None,
            &Province::Tunis => None,
            &Province::Denmark => None,
            &Province::AdriaticSea => None,
            &Province::AegeanSea => None,
            &Province::BalticSea => None,
            &Province::BarentsSea => None,
            &Province::BlackSea => None,
            &Province::EasternMediterranean => None,
            &Province::EnglishChannel => None,
            &Province::GulfOfBothnia => None,
            &Province::GulfOfLyon => None,
            &Province::HeligolandBight => None,
            &Province::IonianSea => None,
            &Province::IrishSea => None,
            &Province::MidAtlanticOcean => None,
            &Province::NorthAtlanticOcean => None,
            &Province::NorthSea => None,
            &Province::NorwegianSea => None,
            &Province::Skagerrak => None,
            &Province::TyrrhenianSea => None,
            &Province::WesternMediterranean => None,
        }
    }
    fn supply_center(&self) -> bool {
        match &self {
            &Province::Bohemia => false,
            &Province::Budapest => true,
            &Province::Galicia => false,
            &Province::Trieste => true,
            &Province::Tyrolia => false,
            &Province::Vienna => true,
            &Province::Clyde => false,
            &Province::Edinburgh => true,
            &Province::Liverpool => true,
            &Province::London => true,
            &Province::Wales => false,
            &Province::Yorkshire => false,
            &Province::Brest => true,
            &Province::Burgundy => false,
            &Province::Gascony => false,
            &Province::Marseilles => true,
            &Province::Paris => true,
            &Province::Picardy => false,
            &Province::Berlin => true,
            &Province::Kiel => true,
            &Province::Munich => true,
            &Province::Prussia => false,
            &Province::Ruhr => false,
            &Province::Silesia => false,
            &Province::Apulia => false,
            &Province::Naples => true,
            &Province::Piedmont => false,
            &Province::Rome => true,
            &Province::Tuscany => false,
            &Province::Venice => true,
            &Province::Livonia => false,
            &Province::Moscow => true,
            &Province::Sevastopol => true,
            &Province::StPetersburg => true,
            &Province::Ukraine => false,
            &Province::Warsaw => true,
            &Province::Ankara => true,
            &Province::Armenia => false,
            &Province::Constantinople => true,
            &Province::Smyrna => true,
            &Province::Syria => false,
            &Province::Albania => false,
            &Province::Belgium => true,
            &Province::Bulgaria => true,
            &Province::Finland => false,
            &Province::Greece => true,
            &Province::Holland => true,
            &Province::Norway => true,
            &Province::NorthAfrica => false,
            &Province::Portugal => true,
            &Province::Rumania => true,
            &Province::Serbia => true,
            &Province::Spain => true,
            &Province::Sweden => true,
            &Province::Tunis => true,
            &Province::Denmark => true,
            &Province::AdriaticSea => false,
            &Province::AegeanSea => false,
            &Province::BalticSea => false,
            &Province::BarentsSea => false,
            &Province::BlackSea => false,
            &Province::EasternMediterranean => false,
            &Province::EnglishChannel => false,
            &Province::GulfOfBothnia => false,
            &Province::GulfOfLyon => false,
            &Province::HeligolandBight => false,
            &Province::IonianSea => false,
            &Province::IrishSea => false,
            &Province::MidAtlanticOcean => false,
            &Province::NorthAtlanticOcean => false,
            &Province::NorthSea => false,
            &Province::NorwegianSea => false,
            &Province::Skagerrak => false,
            &Province::TyrrhenianSea => false,
            &Province::WesternMediterranean => false,
        }
    }
    fn terrain(&self) -> super::terrain::Terrain {
        match &self {
            &Province::Bohemia => super::terrain::Terrain::Inland,
            &Province::Budapest => super::terrain::Terrain::Inland,
            &Province::Galicia => super::terrain::Terrain::Inland,
            &Province::Trieste => super::terrain::Terrain::Coastal,
            &Province::Tyrolia => super::terrain::Terrain::Inland,
            &Province::Vienna => super::terrain::Terrain::Inland,
            &Province::Clyde => super::terrain::Terrain::Coastal,
            &Province::Edinburgh => super::terrain::Terrain::Coastal,
            &Province::Liverpool => super::terrain::Terrain::Coastal,
            &Province::London => super::terrain::Terrain::Coastal,
            &Province::Wales => super::terrain::Terrain::Coastal,
            &Province::Yorkshire => super::terrain::Terrain::Coastal,
            &Province::Brest => super::terrain::Terrain::Coastal,
            &Province::Burgundy => super::terrain::Terrain::Inland,
            &Province::Gascony => super::terrain::Terrain::Coastal,
            &Province::Marseilles => super::terrain::Terrain::Coastal,
            &Province::Paris => super::terrain::Terrain::Inland,
            &Province::Picardy => super::terrain::Terrain::Coastal,
            &Province::Berlin => super::terrain::Terrain::Coastal,
            &Province::Kiel => super::terrain::Terrain::Coastal,
            &Province::Munich => super::terrain::Terrain::Inland,
            &Province::Prussia => super::terrain::Terrain::Coastal,
            &Province::Ruhr => super::terrain::Terrain::Inland,
            &Province::Silesia => super::terrain::Terrain::Inland,
            &Province::Apulia => super::terrain::Terrain::Coastal,
            &Province::Naples => super::terrain::Terrain::Coastal,
            &Province::Piedmont => super::terrain::Terrain::Coastal,
            &Province::Rome => super::terrain::Terrain::Coastal,
            &Province::Tuscany => super::terrain::Terrain::Coastal,
            &Province::Venice => super::terrain::Terrain::Coastal,
            &Province::Livonia => super::terrain::Terrain::Coastal,
            &Province::Moscow => super::terrain::Terrain::Inland,
            &Province::Sevastopol => super::terrain::Terrain::Coastal,
            &Province::StPetersburg => super::terrain::Terrain::Coastal,
            &Province::Ukraine => super::terrain::Terrain::Inland,
            &Province::Warsaw => super::terrain::Terrain::Inland,
            &Province::Ankara => super::terrain::Terrain::Coastal,
            &Province::Armenia => super::terrain::Terrain::Coastal,
            &Province::Constantinople => super::terrain::Terrain::Coastal,
            &Province::Smyrna => super::terrain::Terrain::Coastal,
            &Province::Syria => super::terrain::Terrain::Coastal,
            &Province::Albania => super::terrain::Terrain::Coastal,
            &Province::Belgium => super::terrain::Terrain::Coastal,
            &Province::Bulgaria => super::terrain::Terrain::Coastal,
            &Province::Finland => super::terrain::Terrain::Coastal,
            &Province::Greece => super::terrain::Terrain::Coastal,
            &Province::Holland => super::terrain::Terrain::Coastal,
            &Province::Norway => super::terrain::Terrain::Coastal,
            &Province::NorthAfrica => super::terrain::Terrain::Coastal,
            &Province::Portugal => super::terrain::Terrain::Coastal,
            &Province::Rumania => super::terrain::Terrain::Coastal,
            &Province::Serbia => super::terrain::Terrain::Inland,
            &Province::Spain => super::terrain::Terrain::Coastal,
            &Province::Sweden => super::terrain::Terrain::Coastal,
            &Province::Tunis => super::terrain::Terrain::Coastal,
            &Province::Denmark => super::terrain::Terrain::Coastal,
            &Province::AdriaticSea => super::terrain::Terrain::Water,
            &Province::AegeanSea => super::terrain::Terrain::Water,
            &Province::BalticSea => super::terrain::Terrain::Water,
            &Province::BarentsSea => super::terrain::Terrain::Water,
            &Province::BlackSea => super::terrain::Terrain::Water,
            &Province::EasternMediterranean => super::terrain::Terrain::Water,
            &Province::EnglishChannel => super::terrain::Terrain::Water,
            &Province::GulfOfBothnia => super::terrain::Terrain::Water,
            &Province::GulfOfLyon => super::terrain::Terrain::Water,
            &Province::HeligolandBight => super::terrain::Terrain::Water,
            &Province::IonianSea => super::terrain::Terrain::Water,
            &Province::IrishSea => super::terrain::Terrain::Water,
            &Province::MidAtlanticOcean => super::terrain::Terrain::Water,
            &Province::NorthAtlanticOcean => super::terrain::Terrain::Water,
            &Province::NorthSea => super::terrain::Terrain::Water,
            &Province::NorwegianSea => super::terrain::Terrain::Water,
            &Province::Skagerrak => super::terrain::Terrain::Water,
            &Province::TyrrhenianSea => super::terrain::Terrain::Water,
            &Province::WesternMediterranean => super::terrain::Terrain::Water,
        }
    }
}

