use crate::supply_center::SupplyCenter;

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Province {
    AdriaticSea,
    AegeanSea,
    Albania,
    Ankara,
    Apulia,
    Armenia,
    BalticSea,
    BarentsSea,
    Belgium,
    Berlin,
    BlackSea,
    Bohemia,
    Brest,
    Budapest,
    Bulgaria,
    Burgundy,
    Clyde,
    Constantinople,
    Denmark,
    EasternMediterranean,
    Edinburgh,
    EnglishChannel,
    Finland,
    Galicia,
    Gascony,
    Greece,
    GulfOfBothnia,
    GulfOfLyon,
    HeligolandBight,
    Holland,
    IonianSea,
    IrishSea,
    Kiel,
    Liverpool,
    Livonia,
    London,
    Marseilles,
    MidAtlanticOcean,
    Moscow,
    Munich,
    Naples,
    NorthAfrica,
    NorthAtlanticOcean,
    NorthSea,
    Norway,
    NorwegianSea,
    Paris,
    Picardy,
    Piedmont,
    Portugal,
    Prussia,
    Rome,
    Ruhr,
    Rumania,
    Serbia,
    Sevastopol,
    Silesia,
    Skagerrak,
    Smyrna,
    Spain,
    StPetersburg,
    Sweden,
    Syria,
    Trieste,
    Tunis,
    Tuscany,
    Tyrolia,
    TyrrhenianSea,
    Ukraine,
    Venice,
    Vienna,
    Wales,
    Warsaw,
    WesternMediterranean,
    Yorkshire,
}

impl core::fmt::Display for Province {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match &self {
            &Province::AdriaticSea => write!(f, "Adriatic Sea"),
            &Province::AegeanSea => write!(f, "Aegean Sea"),
            &Province::Albania => write!(f, "Albania"),
            &Province::Ankara => write!(f, "Ankara"),
            &Province::Apulia => write!(f, "Apulia"),
            &Province::Armenia => write!(f, "Armenia"),
            &Province::BalticSea => write!(f, "Baltic Sea"),
            &Province::BarentsSea => write!(f, "Barents Sea"),
            &Province::Belgium => write!(f, "Belgium"),
            &Province::Berlin => write!(f, "Berlin"),
            &Province::BlackSea => write!(f, "Black Sea"),
            &Province::Bohemia => write!(f, "Bohemia"),
            &Province::Brest => write!(f, "Brest"),
            &Province::Budapest => write!(f, "Budapest"),
            &Province::Bulgaria => write!(f, "Bulgaria"),
            &Province::Burgundy => write!(f, "Burgundy"),
            &Province::Clyde => write!(f, "Clyde"),
            &Province::Constantinople => write!(f, "Constantinople"),
            &Province::Denmark => write!(f, "Denmark"),
            &Province::EasternMediterranean => write!(f, "Eastern Mediterranean"),
            &Province::Edinburgh => write!(f, "Edinburgh"),
            &Province::EnglishChannel => write!(f, "English Channel"),
            &Province::Finland => write!(f, "Finland"),
            &Province::Galicia => write!(f, "Galicia"),
            &Province::Gascony => write!(f, "Gascony"),
            &Province::Greece => write!(f, "Greece"),
            &Province::GulfOfBothnia => write!(f, "Gulf of Bothnia"),
            &Province::GulfOfLyon => write!(f, "Gulf of Lyon"),
            &Province::HeligolandBight => write!(f, "Heligoland Bight"),
            &Province::Holland => write!(f, "Holland"),
            &Province::IonianSea => write!(f, "Ionian Sea"),
            &Province::IrishSea => write!(f, "Irish Sea"),
            &Province::Kiel => write!(f, "Kiel"),
            &Province::Liverpool => write!(f, "Liverpool"),
            &Province::Livonia => write!(f, "Livonia"),
            &Province::London => write!(f, "London"),
            &Province::Marseilles => write!(f, "Marseilles"),
            &Province::MidAtlanticOcean => write!(f, "Mid-Atlantic Ocean"),
            &Province::Moscow => write!(f, "Moscow"),
            &Province::Munich => write!(f, "Munich"),
            &Province::Naples => write!(f, "Naples"),
            &Province::NorthAfrica => write!(f, "North Africa"),
            &Province::NorthAtlanticOcean => write!(f, "North Atlantic Ocean"),
            &Province::NorthSea => write!(f, "North Sea"),
            &Province::Norway => write!(f, "Norway"),
            &Province::NorwegianSea => write!(f, "Norwegian Sea"),
            &Province::Paris => write!(f, "Paris"),
            &Province::Picardy => write!(f, "Picardy"),
            &Province::Piedmont => write!(f, "Piedmont"),
            &Province::Portugal => write!(f, "Portugal"),
            &Province::Prussia => write!(f, "Prussia"),
            &Province::Rome => write!(f, "Rome"),
            &Province::Ruhr => write!(f, "Ruhr"),
            &Province::Rumania => write!(f, "Rumania"),
            &Province::Serbia => write!(f, "Serbia"),
            &Province::Sevastopol => write!(f, "Sevastopol"),
            &Province::Silesia => write!(f, "Silesia"),
            &Province::Skagerrak => write!(f, "Skagerrak"),
            &Province::Smyrna => write!(f, "Smyrna"),
            &Province::Spain => write!(f, "Spain"),
            &Province::StPetersburg => write!(f, "St Petersburg"),
            &Province::Sweden => write!(f, "Sweden"),
            &Province::Syria => write!(f, "Syria"),
            &Province::Trieste => write!(f, "Trieste"),
            &Province::Tunis => write!(f, "Tunis"),
            &Province::Tuscany => write!(f, "Tuscany"),
            &Province::Tyrolia => write!(f, "Tyrolia"),
            &Province::TyrrhenianSea => write!(f, "Tyrrhenian Sea"),
            &Province::Ukraine => write!(f, "Ukraine"),
            &Province::Venice => write!(f, "Venice"),
            &Province::Vienna => write!(f, "Vienna"),
            &Province::Wales => write!(f, "Wales"),
            &Province::Warsaw => write!(f, "Warsaw"),
            &Province::WesternMediterranean => write!(f, "Western Mediterranean"),
            &Province::Yorkshire => write!(f, "Yorkshire"),
        }
    }
}

impl Province {
    pub fn country(&self) -> Option<super::country::Country> {
        match &self {
            &Province::AdriaticSea => None,
            &Province::AegeanSea => None,
            &Province::Albania => None,
            &Province::Ankara => Some(super::country::Country::Turkey),
            &Province::Apulia => Some(super::country::Country::Italy),
            &Province::Armenia => Some(super::country::Country::Turkey),
            &Province::BalticSea => None,
            &Province::BarentsSea => None,
            &Province::Belgium => None,
            &Province::Berlin => Some(super::country::Country::Germany),
            &Province::BlackSea => None,
            &Province::Bohemia => Some(super::country::Country::Austria),
            &Province::Brest => Some(super::country::Country::France),
            &Province::Budapest => Some(super::country::Country::Austria),
            &Province::Bulgaria => None,
            &Province::Burgundy => Some(super::country::Country::France),
            &Province::Clyde => Some(super::country::Country::England),
            &Province::Constantinople => Some(super::country::Country::Turkey),
            &Province::Denmark => None,
            &Province::EasternMediterranean => None,
            &Province::Edinburgh => Some(super::country::Country::England),
            &Province::EnglishChannel => None,
            &Province::Finland => None,
            &Province::Galicia => Some(super::country::Country::Austria),
            &Province::Gascony => Some(super::country::Country::France),
            &Province::Greece => None,
            &Province::GulfOfBothnia => None,
            &Province::GulfOfLyon => None,
            &Province::HeligolandBight => None,
            &Province::Holland => None,
            &Province::IonianSea => None,
            &Province::IrishSea => None,
            &Province::Kiel => Some(super::country::Country::Germany),
            &Province::Liverpool => Some(super::country::Country::England),
            &Province::Livonia => Some(super::country::Country::Russia),
            &Province::London => Some(super::country::Country::England),
            &Province::Marseilles => Some(super::country::Country::France),
            &Province::MidAtlanticOcean => None,
            &Province::Moscow => Some(super::country::Country::Russia),
            &Province::Munich => Some(super::country::Country::Germany),
            &Province::Naples => Some(super::country::Country::Italy),
            &Province::NorthAfrica => None,
            &Province::NorthAtlanticOcean => None,
            &Province::NorthSea => None,
            &Province::Norway => None,
            &Province::NorwegianSea => None,
            &Province::Paris => Some(super::country::Country::France),
            &Province::Picardy => Some(super::country::Country::France),
            &Province::Piedmont => Some(super::country::Country::Italy),
            &Province::Portugal => None,
            &Province::Prussia => Some(super::country::Country::Germany),
            &Province::Rome => Some(super::country::Country::Italy),
            &Province::Ruhr => Some(super::country::Country::Germany),
            &Province::Rumania => None,
            &Province::Serbia => None,
            &Province::Sevastopol => Some(super::country::Country::Russia),
            &Province::Silesia => Some(super::country::Country::Germany),
            &Province::Skagerrak => None,
            &Province::Smyrna => Some(super::country::Country::Turkey),
            &Province::Spain => None,
            &Province::StPetersburg => Some(super::country::Country::Russia),
            &Province::Sweden => None,
            &Province::Syria => Some(super::country::Country::Turkey),
            &Province::Trieste => Some(super::country::Country::Austria),
            &Province::Tunis => None,
            &Province::Tuscany => Some(super::country::Country::Italy),
            &Province::Tyrolia => Some(super::country::Country::Austria),
            &Province::TyrrhenianSea => None,
            &Province::Ukraine => Some(super::country::Country::Russia),
            &Province::Venice => Some(super::country::Country::Italy),
            &Province::Vienna => Some(super::country::Country::Austria),
            &Province::Wales => Some(super::country::Country::England),
            &Province::Warsaw => Some(super::country::Country::Russia),
            &Province::WesternMediterranean => None,
            &Province::Yorkshire => Some(super::country::Country::England),
        }
    }
    pub fn supply_center(&self) -> Option<SupplyCenter> {
        match &self {
            &Province::AdriaticSea => None,
            &Province::AegeanSea => None,
            &Province::Albania => None,
            &Province::Ankara => Some(SupplyCenter::Ankara),
            &Province::Apulia => None,
            &Province::Armenia => None,
            &Province::BalticSea => None,
            &Province::BarentsSea => None,
            &Province::Belgium => Some(SupplyCenter::Belgium),
            &Province::Berlin => Some(SupplyCenter::Berlin),
            &Province::BlackSea => None,
            &Province::Bohemia => None,
            &Province::Brest => Some(SupplyCenter::Brest),
            &Province::Budapest => Some(SupplyCenter::Budapest),
            &Province::Bulgaria => Some(SupplyCenter::Bulgaria),
            &Province::Burgundy => None,
            &Province::Clyde => None,
            &Province::Constantinople => Some(SupplyCenter::Constantinople),
            &Province::Denmark => Some(SupplyCenter::Denmark),
            &Province::EasternMediterranean => None,
            &Province::Edinburgh => Some(SupplyCenter::Edinburgh),
            &Province::EnglishChannel => None,
            &Province::Finland => None,
            &Province::Galicia => None,
            &Province::Gascony => None,
            &Province::Greece => Some(SupplyCenter::Greece),
            &Province::GulfOfBothnia => None,
            &Province::GulfOfLyon => None,
            &Province::HeligolandBight => None,
            &Province::Holland => Some(SupplyCenter::Holland),
            &Province::IonianSea => None,
            &Province::IrishSea => None,
            &Province::Kiel => Some(SupplyCenter::Kiel),
            &Province::Liverpool => Some(SupplyCenter::Liverpool),
            &Province::Livonia => None,
            &Province::London => Some(SupplyCenter::London),
            &Province::Marseilles => Some(SupplyCenter::Marseilles),
            &Province::MidAtlanticOcean => None,
            &Province::Moscow => Some(SupplyCenter::Moscow),
            &Province::Munich => Some(SupplyCenter::Munich),
            &Province::Naples => Some(SupplyCenter::Naples),
            &Province::NorthAfrica => None,
            &Province::NorthAtlanticOcean => None,
            &Province::NorthSea => None,
            &Province::Norway => Some(SupplyCenter::Norway),
            &Province::NorwegianSea => None,
            &Province::Paris => Some(SupplyCenter::Paris),
            &Province::Picardy => None,
            &Province::Piedmont => None,
            &Province::Portugal => Some(SupplyCenter::Portugal),
            &Province::Prussia => None,
            &Province::Rome => Some(SupplyCenter::Rome),
            &Province::Ruhr => None,
            &Province::Rumania => Some(SupplyCenter::Rumania),
            &Province::Serbia => Some(SupplyCenter::Serbia),
            &Province::Sevastopol => Some(SupplyCenter::Sevastopol),
            &Province::Silesia => None,
            &Province::Skagerrak => None,
            &Province::Smyrna => Some(SupplyCenter::Smyrna),
            &Province::Spain => Some(SupplyCenter::Spain),
            &Province::StPetersburg => Some(SupplyCenter::StPetersburg),
            &Province::Sweden => Some(SupplyCenter::Sweden),
            &Province::Syria => None,
            &Province::Trieste => Some(SupplyCenter::Trieste),
            &Province::Tunis => Some(SupplyCenter::Tunis),
            &Province::Tuscany => None,
            &Province::Tyrolia => None,
            &Province::TyrrhenianSea => None,
            &Province::Ukraine => None,
            &Province::Venice => Some(SupplyCenter::Venice),
            &Province::Vienna => Some(SupplyCenter::Vienna),
            &Province::Wales => None,
            &Province::Warsaw => Some(SupplyCenter::Warsaw),
            &Province::WesternMediterranean => None,
            &Province::Yorkshire => None,
        }
    }
    pub fn terrain(&self) -> super::terrain::Terrain {
        match &self {
            &Province::AdriaticSea => super::terrain::Terrain::Water,
            &Province::AegeanSea => super::terrain::Terrain::Water,
            &Province::Albania => super::terrain::Terrain::Coastal,
            &Province::Ankara => super::terrain::Terrain::Coastal,
            &Province::Apulia => super::terrain::Terrain::Coastal,
            &Province::Armenia => super::terrain::Terrain::Coastal,
            &Province::BalticSea => super::terrain::Terrain::Water,
            &Province::BarentsSea => super::terrain::Terrain::Water,
            &Province::Belgium => super::terrain::Terrain::Coastal,
            &Province::Berlin => super::terrain::Terrain::Coastal,
            &Province::BlackSea => super::terrain::Terrain::Water,
            &Province::Bohemia => super::terrain::Terrain::Inland,
            &Province::Brest => super::terrain::Terrain::Coastal,
            &Province::Budapest => super::terrain::Terrain::Inland,
            &Province::Bulgaria => super::terrain::Terrain::Coastal,
            &Province::Burgundy => super::terrain::Terrain::Inland,
            &Province::Clyde => super::terrain::Terrain::Coastal,
            &Province::Constantinople => super::terrain::Terrain::Coastal,
            &Province::Denmark => super::terrain::Terrain::Coastal,
            &Province::EasternMediterranean => super::terrain::Terrain::Water,
            &Province::Edinburgh => super::terrain::Terrain::Coastal,
            &Province::EnglishChannel => super::terrain::Terrain::Water,
            &Province::Finland => super::terrain::Terrain::Coastal,
            &Province::Galicia => super::terrain::Terrain::Inland,
            &Province::Gascony => super::terrain::Terrain::Coastal,
            &Province::Greece => super::terrain::Terrain::Coastal,
            &Province::GulfOfBothnia => super::terrain::Terrain::Water,
            &Province::GulfOfLyon => super::terrain::Terrain::Water,
            &Province::HeligolandBight => super::terrain::Terrain::Water,
            &Province::Holland => super::terrain::Terrain::Coastal,
            &Province::IonianSea => super::terrain::Terrain::Water,
            &Province::IrishSea => super::terrain::Terrain::Water,
            &Province::Kiel => super::terrain::Terrain::Coastal,
            &Province::Liverpool => super::terrain::Terrain::Coastal,
            &Province::Livonia => super::terrain::Terrain::Coastal,
            &Province::London => super::terrain::Terrain::Coastal,
            &Province::Marseilles => super::terrain::Terrain::Coastal,
            &Province::MidAtlanticOcean => super::terrain::Terrain::Water,
            &Province::Moscow => super::terrain::Terrain::Inland,
            &Province::Munich => super::terrain::Terrain::Inland,
            &Province::Naples => super::terrain::Terrain::Coastal,
            &Province::NorthAfrica => super::terrain::Terrain::Coastal,
            &Province::NorthAtlanticOcean => super::terrain::Terrain::Water,
            &Province::NorthSea => super::terrain::Terrain::Water,
            &Province::Norway => super::terrain::Terrain::Coastal,
            &Province::NorwegianSea => super::terrain::Terrain::Water,
            &Province::Paris => super::terrain::Terrain::Inland,
            &Province::Picardy => super::terrain::Terrain::Coastal,
            &Province::Piedmont => super::terrain::Terrain::Coastal,
            &Province::Portugal => super::terrain::Terrain::Coastal,
            &Province::Prussia => super::terrain::Terrain::Coastal,
            &Province::Rome => super::terrain::Terrain::Coastal,
            &Province::Ruhr => super::terrain::Terrain::Inland,
            &Province::Rumania => super::terrain::Terrain::Coastal,
            &Province::Serbia => super::terrain::Terrain::Inland,
            &Province::Sevastopol => super::terrain::Terrain::Coastal,
            &Province::Silesia => super::terrain::Terrain::Inland,
            &Province::Skagerrak => super::terrain::Terrain::Water,
            &Province::Smyrna => super::terrain::Terrain::Coastal,
            &Province::Spain => super::terrain::Terrain::Coastal,
            &Province::StPetersburg => super::terrain::Terrain::Coastal,
            &Province::Sweden => super::terrain::Terrain::Coastal,
            &Province::Syria => super::terrain::Terrain::Coastal,
            &Province::Trieste => super::terrain::Terrain::Coastal,
            &Province::Tunis => super::terrain::Terrain::Coastal,
            &Province::Tuscany => super::terrain::Terrain::Coastal,
            &Province::Tyrolia => super::terrain::Terrain::Inland,
            &Province::TyrrhenianSea => super::terrain::Terrain::Water,
            &Province::Ukraine => super::terrain::Terrain::Inland,
            &Province::Venice => super::terrain::Terrain::Coastal,
            &Province::Vienna => super::terrain::Terrain::Inland,
            &Province::Wales => super::terrain::Terrain::Coastal,
            &Province::Warsaw => super::terrain::Terrain::Inland,
            &Province::WesternMediterranean => super::terrain::Terrain::Water,
            &Province::Yorkshire => super::terrain::Terrain::Coastal,
        }
    }
}
