use crate::province::Province;
use serde::Deserialize;

#[derive(Copy, Clone, Debug, Deserialize, PartialEq, Eq, Hash)]
pub enum SupplyCenter {
    Ankara,
    Belgium,
    Berlin,
    Brest,
    Budapest,
    Bulgaria,
    Constantinople,
    Denmark,
    Edinburgh,
    Greece,
    Holland,
    Kiel,
    Liverpool,
    London,
    Marseilles,
    Moscow,
    Munich,
    Naples,
    Norway,
    Paris,
    Portugal,
    Rome,
    Rumania,
    Serbia,
    Sevastopol,
    Smyrna,
    Spain,
    StPetersburg,
    Sweden,
    Trieste,
    Tunis,
    Venice,
    Vienna,
    Warsaw,
}

impl core::fmt::Display for SupplyCenter {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        match &self {
            &SupplyCenter::Ankara => write!(f, "Ankara"),
            &SupplyCenter::Belgium => write!(f, "Belgium"),
            &SupplyCenter::Berlin => write!(f, "Berlin"),
            &SupplyCenter::Brest => write!(f, "Brest"),
            &SupplyCenter::Budapest => write!(f, "Budapest"),
            &SupplyCenter::Bulgaria => write!(f, "Bulgaria"),
            &SupplyCenter::Constantinople => write!(f, "Constantinople"),
            &SupplyCenter::Denmark => write!(f, "Denmark"),
            &SupplyCenter::Edinburgh => write!(f, "Edinburgh"),
            &SupplyCenter::Greece => write!(f, "Greece"),
            &SupplyCenter::Holland => write!(f, "Holland"),
            &SupplyCenter::Kiel => write!(f, "Kiel"),
            &SupplyCenter::Liverpool => write!(f, "Liverpool"),
            &SupplyCenter::London => write!(f, "London"),
            &SupplyCenter::Marseilles => write!(f, "Marseilles"),
            &SupplyCenter::Moscow => write!(f, "Moscow"),
            &SupplyCenter::Munich => write!(f, "Munich"),
            &SupplyCenter::Naples => write!(f, "Naples"),
            &SupplyCenter::Norway => write!(f, "Norway"),
            &SupplyCenter::Paris => write!(f, "Paris"),
            &SupplyCenter::Portugal => write!(f, "Portugal"),
            &SupplyCenter::Rome => write!(f, "Rome"),
            &SupplyCenter::Rumania => write!(f, "Rumania"),
            &SupplyCenter::Serbia => write!(f, "Serbia"),
            &SupplyCenter::Sevastopol => write!(f, "Sevastopol"),
            &SupplyCenter::Smyrna => write!(f, "Smyrna"),
            &SupplyCenter::Spain => write!(f, "Spain"),
            &SupplyCenter::StPetersburg => write!(f, "St Petersburg"),
            &SupplyCenter::Sweden => write!(f, "Sweden"),
            &SupplyCenter::Trieste => write!(f, "Trieste"),
            &SupplyCenter::Tunis => write!(f, "Tunis"),
            &SupplyCenter::Venice => write!(f, "Venice"),
            &SupplyCenter::Vienna => write!(f, "Vienna"),
            &SupplyCenter::Warsaw => write!(f, "Warsaw"),
        }
    }
}

impl SupplyCenter {
    pub fn ident(&self) -> &'static str {
        match &self {
            &SupplyCenter::Ankara => "Ankara",
            &SupplyCenter::Belgium => "Belgium",
            &SupplyCenter::Berlin => "Berlin",
            &SupplyCenter::Brest => "Brest",
            &SupplyCenter::Budapest => "Budapest",
            &SupplyCenter::Bulgaria => "Bulgaria",
            &SupplyCenter::Constantinople => "Constantinople",
            &SupplyCenter::Denmark => "Denmark",
            &SupplyCenter::Edinburgh => "Edinburgh",
            &SupplyCenter::Greece => "Greece",
            &SupplyCenter::Holland => "Holland",
            &SupplyCenter::Kiel => "Kiel",
            &SupplyCenter::Liverpool => "Liverpool",
            &SupplyCenter::London => "London",
            &SupplyCenter::Marseilles => "Marseilles",
            &SupplyCenter::Moscow => "Moscow",
            &SupplyCenter::Munich => "Munich",
            &SupplyCenter::Naples => "Naples",
            &SupplyCenter::Norway => "Norway",
            &SupplyCenter::Paris => "Paris",
            &SupplyCenter::Portugal => "Portugal",
            &SupplyCenter::Rome => "Rome",
            &SupplyCenter::Rumania => "Rumania",
            &SupplyCenter::Serbia => "Serbia",
            &SupplyCenter::Sevastopol => "Sevastopol",
            &SupplyCenter::Smyrna => "Smyrna",
            &SupplyCenter::Spain => "Spain",
            &SupplyCenter::StPetersburg => "StPetersburg",
            &SupplyCenter::Sweden => "Sweden",
            &SupplyCenter::Trieste => "Trieste",
            &SupplyCenter::Tunis => "Tunis",
            &SupplyCenter::Venice => "Venice",
            &SupplyCenter::Vienna => "Vienna",
            &SupplyCenter::Warsaw => "Warsaw",
        }
    }

    pub fn province(&self) -> Province {
        match &self {
            &SupplyCenter::Ankara => Province::Ankara,
            &SupplyCenter::Belgium => Province::Belgium,
            &SupplyCenter::Berlin => Province::Berlin,
            &SupplyCenter::Brest => Province::Brest,
            &SupplyCenter::Budapest => Province::Budapest,
            &SupplyCenter::Bulgaria => Province::Bulgaria,
            &SupplyCenter::Constantinople => Province::Constantinople,
            &SupplyCenter::Denmark => Province::Denmark,
            &SupplyCenter::Edinburgh => Province::Edinburgh,
            &SupplyCenter::Greece => Province::Greece,
            &SupplyCenter::Holland => Province::Holland,
            &SupplyCenter::Kiel => Province::Kiel,
            &SupplyCenter::Liverpool => Province::Liverpool,
            &SupplyCenter::London => Province::London,
            &SupplyCenter::Marseilles => Province::Marseilles,
            &SupplyCenter::Moscow => Province::Moscow,
            &SupplyCenter::Munich => Province::Munich,
            &SupplyCenter::Naples => Province::Naples,
            &SupplyCenter::Norway => Province::Norway,
            &SupplyCenter::Paris => Province::Paris,
            &SupplyCenter::Portugal => Province::Portugal,
            &SupplyCenter::Rome => Province::Rome,
            &SupplyCenter::Rumania => Province::Rumania,
            &SupplyCenter::Serbia => Province::Serbia,
            &SupplyCenter::Sevastopol => Province::Sevastopol,
            &SupplyCenter::Smyrna => Province::Smyrna,
            &SupplyCenter::Spain => Province::Spain,
            &SupplyCenter::StPetersburg => Province::StPetersburg,
            &SupplyCenter::Sweden => Province::Sweden,
            &SupplyCenter::Trieste => Province::Trieste,
            &SupplyCenter::Tunis => Province::Tunis,
            &SupplyCenter::Venice => Province::Venice,
            &SupplyCenter::Vienna => Province::Vienna,
            &SupplyCenter::Warsaw => Province::Warsaw,
        }
    }
}
